global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['config-server:8888']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'policy-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['policy-service:8080']

  - job_name: 'claim-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['claim-service:8080']

  - job_name: 'adjuster-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['adjuster-service:8080']

  - job_name: 'coverage-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coverage-service:8080']

  - job_name: 'report-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['report-service:8080']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']